import React from 'react';

const Footer = () => {
    return (
        <div className='bg-black text-white p-5'>
            <h1>Footer page</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quasi quidem reprehenderit itaque nam totam dolore rem aut, voluptas ducimus laborum minima nihil temporibus facilis iure distinctio, officiis, minus laboriosam iusto. Quaerat incidunt nesciunt corrupti similique consequuntur inventore qui non in velit mollitia nihil, ex nemo maxime delectus aliquam, saepe corporis ut cum labore eveniet omnis recusandae. Voluptas officia numquam sequi autem expedita quae eligendi molestias sed temporibus impedit! Commodi vel exercitationem minima fugiat tenetur asperiores porro, nesciunt explicabo excepturi voluptatem maiores pariatur natus ab quae nobis eligendi laudantium aperiam numquam suscipit. Sint atque exercitationem tenetur perferendis sunt officia sequi, esse libero excepturi soluta dolorum alias, assumenda nihil. Vel architecto esse quibusdam, molestias fuga molestiae nulla perferendis aspernatur eius consectetur sint numquam obcaecati laudantium delectus deleniti earum praesentium temporibus dicta quia commodi cupiditate quo reiciendis magnam facilis? Quos vel expedita consectetur, ipsam cupiditate mollitia, ex amet temporibus qui nulla distinctio perspiciatis quisquam suscipit optio facilis vitae praesentium eius assumenda, provident doloribus aperiam error harum fugiat. Est ducimus voluptatum voluptatibus incidunt voluptas, repudiandae neque. Ducimus sint reiciendis illum id animi autem dicta hic molestiae aliquid non dolore nemo quaerat, neque voluptates nam odio ut? Dolorem ullam eligendi quia cum numquam non repudiandae tempora vero rerum. Possimus aut sunt repudiandae earum asperiores id in reiciendis consectetur cum impedit ut, corrupti eaque vel. Ducimus, enim a. Ipsum minus numquam saepe nemo, odio animi? Eum nisi ullam dolor ducimus! Magni suscipit magnam aperiam ipsa, similique velit quas, eaque architecto doloribus voluptatum laboriosam asperiores nobis nemo reiciendis perferendis nulla soluta qui a ratione doloremque consectetur voluptate? Necessitatibus delectus, dolore magni repudiandae, sed ex accusantium voluptatibus deserunt dicta temporibus eum laborum, at architecto iure aut ipsum ea! Rem repellat est id ipsam ullam libero nostrum sunt eaque, repudiandae temporibus, vero officiis expedita amet sapiente pariatur earum velit unde at fugiat sed delectus sequi vitae illo? Laudantium reiciendis neque modi at doloribus! Numquam, asperiores a aperiam modi sequi nostrum quod deserunt animi saepe cupiditate perspiciatis cumque quo tempore porro impedit quia iusto necessitatibus .</p>
        </div>
    );
};

export default Footer;